config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'occasions#index'

  resources :articles
  resources :occasions
  resources :packages

  get '/select-date-for-planner' => 'packages#select_date_for_package'
  get '/add-to-planner' => 'packages#add_to_planner'
  get '/my-planner' => 'packages#my_planner'
  post '/place-order' => 'packages#place_order'
  get '/dashboard' => 'dealers#dashboard'
  get 'block_date_for_package' => 'dealers#block_date_for_package'
  get '/block_date' => 'dealers#block_date'
  get '/my-packages' => 'dealers#my_packages'
  post '/update_block_date' => 'dealers#update_block_date'
  post '/confirm-order' => 'dealers#confirm_order'
  post '/package-ratings' => 'packages#ratings'

end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController
	before_action :authenticate_user!
	before_action :is_dealer?

	def dashboard
		@packages = current_user.packages
	end

	def block_date_for_package
		@packages = Package.where(user_id: current_user.id)
	end

	def block_date
		@package = Package.find(params[:package])
	end

	def update_block_date
		package = Package.find(params[:package])
		block_dates = params[:block_date].split(',')
		block_dates.each { |date| package.block_dates << date }
		package.block_dates.uniq!
		if package.save
			flash[:success] = 'The dates have been succesfully blocked'
			redirect_to my_packages_path
		else
			flash[:alert] = 'The dates were unable to block'
			redirect_to dashboard_path
		end
	end

	def my_packages
		@packages = current_user.packages
	end

	def confirm_order
		order = Order.find(params[:order])
		order.is_confirmed = true
		if order.save
			flash[:success] = 'The Order has been confirmed by you'
		else
			flash[:alert] = 'Dear Dealer, We couldn\'t process your request'
		end
		redirect_to dashboard_path
	end

	private

	def is_dealer?
		unless current_user.is_dealer?
			flash[:alert] = 'You are unauthorized to be a Dealer'
			redirect_to root_path
		end
	end
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/views/dealers/block_date.slim
.container
	h2.text-firebrick.text-center = "Block date for package #{@package.name}"
.calendar-planner.text-center
	= link_to 'X', :back, class: 'calendar-close pull-right'

	= month_calendar do |date|
	 	= link_to date.day, '#', class: 'block-date'
	 	.get-date.hide
	 		= date

	= simple_form_for '', url: update_block_date_path do |f|
		= f.input :block_date
		= f.input :package, input_html: { value: @package.id }
		= f.button :submit, 'Confirm', class: 'btn btn-primary'
	end

app/views/dealers/block_date_for_package.slim
.container
	.row
		.col-sm-6
			- @packages.each do |package|
				h3 = package.name
				= link_to 'Block Date', block_date_path(package: package), class: 'btn btn-danger'

app/views/dealers/dashboard.slim
.container
	.row
		.col-sm-3
			ul#dealer-dashboard role="tablist"
				.spacer-xs-30
				li.dashboard-static-tab
					= link_to 'Dashboard', '#'
				.spacer-xs-20
				li.active role="presentation"
					= link_to 'Orders', '#ios', data: { toggle: 'tab' }, role: 'tab'
				li role="presentation"
					= link_to 'Packages', '#android', data: { toggle: 'tab' }, role: 'tab'
				li 
					= link_to 'New Package', new_package_path
				li
					= link_to 'Block Dates', block_date_for_package_path

		.col-sm-9
			.tab-content
			 	#ios.tab-pane.active role='tabpanel'
			 		.spacer-sm-40
			 		table.table.table-type-1.text-uppercase
			 			tr 
			 				th Number of Orders
			 				- orders = @packages.map { |package| package.orders.count } 
			 				th = orders.sum
					- @packages.each do |package|
						table.table.table-striped
							tr
								th Package Name
								th = package.name
							- package.orders.each do |order|
								tr
									th = order.user.email
									th = order.date_reserved
								- if !order.is_confirmed?
									tr
										th = link_to 'Confirm Order', confirm_order_path(order: order.id), method: :post, class: 'btn-firebrick text-center'
						end
					end

			 	#android.tab-pane role='tabpanel'
			 		h2 My Packages
					- @packages.each do |package|
						h2 = package.name
					end