config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'occasions#index'

  resources :articles
  resources :occasions
  resources :packages

  get '/select-date-for-planner' => 'packages#select_date_for_package'
  get '/add-to-planner' => 'packages#add_to_planner'
  get '/my-planner' => 'packages#my_planner'
  post '/place-order' => 'packages#place_order'
  get '/dashboard' => 'dealers#dashboard'
  get 'block_date_for_package' => 'dealers#block_date_for_package'
  get '/block_date' => 'dealers#block_date'
  get '/my-packages' => 'dealers#my_packages'
  post '/update_block_date' => 'dealers#update_block_date'
  post '/confirm-order' => 'dealers#confirm_order'
  post '/package-ratings' => 'packages#ratings'

end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
	has_many :packages, dependent: :destroy	
	has_many :services, through: :packages
	
	serialize :avatar, Array

	def self.services
		services = Service.all
	end
end

app/controllers/occasions_controller.rb
class OccasionsController < ApplicationController
	before_action :authenticate_user!
	before_action :authenticate_user!
	before_action :find_occasion, only: [:show]

	def index
		@occasions = Occasion.all.order(created_at: :asc)
	end

	def show
		@services = Occasion.services
	end

	private

	def find_occasion
		@occasion = Occasion.find(params[:id])
	end

	def occasion_params
		params.permit(:occasion).permit(:name, :guest_size,)
	end
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/views/occasions/index.slim
.container
	.spacer-sm-50
	- @occasions.each_slice(3) do |occasions|
		.row
			- occasions.each do |occasion|
				.col-sm-4.column-content
					.text-center.column-hover-content
						- occasion.avatar.each do |avatar_url|
							= link_to occasion, class: 'display-avatar'
								= cl_image_tag avatar_url
						end
						= link_to occasion.name, occasion, class: 'btn btn-lg navigate-btn text-uppercase'
			end
		.spacer-sm-50

app/views/occasions/show.slim
.container
	.row
		.col-xs-12.text-center.text-firebrick
			h2 = @occasion.name
	.row
		#myCarousel.carousel.slide data-ride="carousel" 
		  ol.carousel-indicators
		    li.active data-slide-to="0" data-target="#myCarousel" 
		    li data-slide-to="1" data-target="#myCarousel" 
		  .carousel-inner role="listbox" 
		    .item.active
		      img src="http://res.cloudinary.com/dnweu15bn/image/upload/v1492799137/nzztm2wzg4v0xcc2j4kv.jpg"
		    .item
		      img src="http://res.cloudinary.com/dnweu15bn/image/upload/v1492799137/nzztm2wzg4v0xcc2j4kv.jpg"
		  a.left.carousel-control data-slide="prev" href="#myCarousel" role="button" 
		    span.glyphicon.glyphicon-chevron-left aria-hidden="true" 
		    span.sr-only Previous
		  a.right.carousel-control data-slide="next" href="#myCarousel" role="button" 
		    span.glyphicon.glyphicon-chevron-right aria-hidden="true" 
		    span.sr-only Next

	.spacer-xs-40    
	- @services.each_slice(3) do |services|
		.row
			- services.each do |service|
				.col-sm-4.column-content
					.text-center.column-hover-content
						- service.avatar.each do |avatar_url|
							= link_to packages_path(service: service.name, occasion: @occasion.name), class: 'display-avatar'
							 	= cl_image_tag avatar_url
						end
						= link_to service.name, packages_path(service: service.name, occasion: @occasion.name), class: 'btn btn-lg navigate-btn text-uppercase'
		.spacer-xs-40
	end