config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'occasions#index'

  resources :articles
  resources :occasions
  resources :packages

  get '/select-date-for-planner' => 'packages#select_date_for_package'
  get '/add-to-planner' => 'packages#add_to_planner'
  get '/my-planner' => 'packages#my_planner'
  post '/place-order' => 'packages#place_order'
  get '/dashboard' => 'dealers#dashboard'
  get 'block_date_for_package' => 'dealers#block_date_for_package'
  get '/block_date' => 'dealers#block_date'
  get '/my-packages' => 'dealers#my_packages'
  post '/update_block_date' => 'dealers#update_block_date'
  post '/confirm-order' => 'dealers#confirm_order'
  post '/package-ratings' => 'packages#ratings'

end

app/views/layouts/_calendar.slim
.spacer-xs-100
.calendar-planner.text-center class=("is-opened" if current_page?(select_date_for_planner_path))

	= month_calendar do |date|
		- is_blocked = @package_blocked_dates.detect { |blocked_date| blocked_date == date }
	 	= link_to date.day, add_to_planner_path(package: params[:package], booking_date: date), class: is_blocked.present? ? 'is-blocked' : 'is-available'

app/views/layouts/_ratings.slim
#rating
	.rating-form.text-center
		= link_to 'X', '#', class: 'pull-right close-rating'
		.ratings-quality
			h3 Quality
			- 5.times do |star|
				= link_to '#', class: "quality-rating-#{star + 1}", data: { rating: star + 1 }
					.glyphicon.glyphicon-star class="rating-star-#{star + 1}"
		.rated-quality.hide

		.ratings-quantity
			h3 Quantity
			- 5.times do |star|
				= link_to '#', class: "quantity-rating-#{star + 1}", data: { rating: star + 1 }
					.glyphicon.glyphicon-star class="rating-star-#{star + 1}"
		.rated-quantity.hide

		.ratings-time			
			h3 Time
			- 5.times do |star|
				= link_to '#', class: "time-rating-#{star + 1}", data: { rating: star + 1 }
					.glyphicon.glyphicon-star class="rating-star-#{star + 1}"
		.rated-time.hide

		= simple_form_for 'rating', url: package_ratings_path, html: { class: 'ratings-input-form' } do |f|
		 	= f.input :quality, label: false, as: :hidden
		 	= f.input :quantity, label: false, as: :hidden
		 	= f.input :time, label: false, as: :hidden
			= f.input :comment, label: false, placeholder: 'Review'
			= f.input :order_id, label: false
			= f.button :submit, 'Submit', class: 'btn-firebrick btn-block'

app/views/layouts/application.slim
doctype html
html
  head
    title Events

    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"

    = stylesheet_link_tag 'application', media: 'all'
    / = stylesheet_link_tag '//cdn.jsdelivr.net/animatecss/3.5.2/animate.min.css'

    = javascript_include_tag 'application'

    = csrf_meta_tags

  body class=('is-background' if user_signed_in?)
    .navbar.navbar-default
      .container
        = link_to  root_path, class: 'navbar-brand text-uppercase' do
          = image_tag 'logo.png'
        .navbar-text.text-uppercase Eventz Made Easy
        ul.pull-right.header-navigation
          li
            = link_to 'Sign Up', new_user_registration_path, class: 'navbar-text text-uppercase' unless user_signed_in?
            = link_to 'Blog', articles_path, class: 'navbar-text text-uppercase'
          - if user_signed_in?
            li 
              = link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'navbar-text text-uppercase'
              = link_to 'My Planner', my_planner_path, class: 'navbar-text text-uppercase'
              = link_to 'Dashboard', dashboard_path, class: 'navbar-text text-uppercase' if current_user.is_dealer?
              = link_to 'New Article', new_article_path, class: 'navbar-text text-uppercase' if current_user.is_author?
          - else
            li = link_to 'Log in', new_user_session_path, class: 'navbar-text text-uppercase'
          end
            
  = flash_messages
= yield